//single-product
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';

//product-list
export const FETCH_PRODUCTS_LIST_START = 'FETCH_PRODUCTS_LIST_START';
export const FETCH_PRODUCTS_LIST_SUCCESS = 'FETCH_PRODUCTS_LIST_SUCCESS';
export const FETCH_PRODUCTS_LIST_FAILED = 'FETCH_PRODUCTS_LIST_FAILED';
export const INCREASE_PAGE = 'INCREASE_PAGE';
export const DECREASE_PAGE = 'DECREASE_PAGE';
export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS';

//page
export const SET_PAGES_COUNT = 'SET_PAGES_COUNT';
